version: "3.9"

services:
  frontend:
    image: app-frontend:dev
    entrypoint: ./dev_entrypoint.sh
    restart: unless-stopped
    ports:
      - 80:3000
    env_file:
      - ./.env.local

    volumes:
      - type: bind
        source: ./
        target: /app

    networks:
      app-network:
        ipv4_address: ${FRONTEND_IP:-172.24.3.1}

networks:
  app-network:
    external: true
